# Generated by Django 3.0 on 2022-08-18 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaruant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('name', models.TextField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('street', models.TextField(max_length=1000)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lng', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
    ]
